apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - port: 3001
      targetPort: 3130
      protocol: TCP            
      nodePort: 31000