apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-depl  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: testdocker:1.0
          env:
            - name: PORT
              value: "4001"
